import React, { useState, useEffect } from 'react';
import { Building2, Save, Globe, Phone, MapPin, Layout, FileText, Loader2, CheckCircle2 } from 'lucide-react';
import axios from 'axios';
import { motion, AnimatePresence } from 'framer-motion';

const BrandingSettings = ({ clinicId }) => {
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [success, setSuccess] = useState(false);
    const [showPreview, setShowPreview] = useState(false);
    const [branding, setBranding] = useState({
        name: '',
        address: '',
        phone: '',
        website: '',
        header_template: '',
        footer_template: 'This report was generated by VoxAI.'
    });

    useEffect(() => {
        if (clinicId) {
            fetchBranding();
        }
    }, [clinicId]);

    const fetchBranding = async () => {
        try {
            const res = await axios.get(`http://localhost:5001/api/clinic/branding/${clinicId}`);
            if (res.data) {
                setBranding(res.data);
            }
        } catch (err) {
            console.error("Failed to fetch branding", err);
        } finally {
            setLoading(false);
        }
    };

    const handleSave = async (e) => {
        e.preventDefault();
        setSaving(true);
        setSuccess(false);
        try {
            const response = await axios.post('http://localhost:5001/api/clinic/branding', {
                id: clinicId,
                ...branding
            });
            if (response.data) {
                setSuccess(true);
                setTimeout(() => setSuccess(false), 3000);
            }
        } catch (err) {
            console.error("Failed to save branding", err);
            const errorMsg = err.response?.data?.error || "Connection error to backend.";
            alert(`Failed to save settings: ${errorMsg}`);
        } finally {
            setSaving(false);
        }
    };

    if (loading) return (
        <div className="flex items-center justify-center p-20">
            <Loader2 className="w-8 h-8 animate-spin text-primary-600" />
        </div>
    );

    return (
        <div className="max-w-4xl mx-auto py-8">
            <div className="mb-8">
                <h2 className="text-2xl font-bold flex items-center gap-3">
                    <Building2 className="text-primary-600" /> Clinic Branding & Templates
                </h2>
                <p className="text-slate-500 mt-1">Customize how your clinic appears on official medical reports and PDFs.</p>
            </div>

            <form onSubmit={handleSave} className="space-y-8">
                {/* Basic Info */}
                <div className="glass-card p-8 space-y-6">
                    <h3 className="text-sm font-bold uppercase tracking-widest text-slate-400 mb-4">Clinic Information</h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                            <label className="block text-sm font-medium text-slate-600 mb-2">Display Name</label>
                            <input
                                type="text"
                                className="input-field"
                                value={branding.name}
                                onChange={(e) => setBranding({ ...branding, name: e.target.value })}
                                placeholder="e.g. Apollo Hospital"
                            />
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-slate-600 mb-2">Website</label>
                            <div className="relative">
                                <Globe className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                                <input
                                    type="text"
                                    className="input-field pl-12"
                                    value={branding.website}
                                    onChange={(e) => setBranding({ ...branding, website: e.target.value })}
                                    placeholder="www.clinic.com"
                                />
                            </div>
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-slate-600 mb-2">Contact Phone</label>
                            <div className="relative">
                                <Phone className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                                <input
                                    type="text"
                                    className="input-field pl-12"
                                    value={branding.phone}
                                    onChange={(e) => setBranding({ ...branding, phone: e.target.value })}
                                    placeholder="+91 ..."
                                />
                            </div>
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-slate-600 mb-2">Clinic Address</label>
                            <div className="relative">
                                <MapPin className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                                <input
                                    type="text"
                                    className="input-field pl-12"
                                    value={branding.address}
                                    onChange={(e) => setBranding({ ...branding, address: e.target.value })}
                                    placeholder="Street, City, State"
                                />
                            </div>
                        </div>
                    </div>
                </div>

                {/* Templates */}
                <div className="glass-card p-8 space-y-6">
                    <h3 className="text-sm font-bold uppercase tracking-widest text-slate-400 mb-4">PDF Report Templates</h3>

                    <div className="flex justify-between items-center mb-6">
                        <label className="block text-sm font-medium text-slate-600 flex items-center gap-2 m-0">
                            <Layout className="w-4 h-4" /> Default Footer Message
                        </label>
                        <button
                            type="button"
                            onClick={() => setShowPreview(!showPreview)}
                            className="text-xs font-bold text-primary-600 hover:text-primary-700 flex items-center gap-2 px-3 py-1.5 bg-primary-50 rounded-lg transition-all border border-primary-100 hover:bg-primary-100 active:scale-95 shadow-sm"
                        >
                            <FileText className="w-3 h-3" />
                            {showPreview ? 'Hide Preview' : 'Preview Report Button'}
                        </button>
                    </div>
                    <textarea
                        className="input-field h-24 resize-none pt-4"
                        value={branding.footer_template}
                        onChange={(e) => setBranding({ ...branding, footer_template: e.target.value })}
                        placeholder="This message will appear at the bottom of every PDF report."
                    />

                    {/* 🏥 Live Preview Section - Conditional */}
                    <AnimatePresence>
                        {showPreview && (
                            <motion.div
                                initial={{ opacity: 0, height: 0 }}
                                animate={{ opacity: 1, height: 'auto' }}
                                exit={{ opacity: 0, height: 0 }}
                                className="overflow-hidden"
                            >
                                <div className="pt-6 border-t border-slate-100 dark:border-slate-800">
                                    <label className="block text-sm font-bold text-slate-400 mb-4 uppercase tracking-widest">Live Report Preview</label>
                                    <div className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-2xl p-0 text-slate-900 font-sans">
                                        <div className="bg-slate-50 border-b border-slate-100 px-4 py-2 flex items-center justify-between">
                                            <span className="text-[10px] font-bold text-slate-400 tracking-tighter uppercase">Output Preview</span>
                                            <div className="flex gap-1">
                                                <div className="w-2 h-2 rounded-full bg-slate-200"></div>
                                                <div className="w-2 h-2 rounded-full bg-slate-200"></div>
                                            </div>
                                        </div>
                                        <div className="p-8">
                                            {/* Header Preview */}
                                            <div className="border-b-2 border-slate-900 pb-4 mb-6">
                                                <h4 className="text-2xl font-black text-slate-900 m-0 tracking-tight">{branding.name || 'CLINIC NAME'}</h4>
                                                <div className="text-[10px] text-slate-500 mt-2 font-medium flex flex-wrap gap-x-3 gap-y-1">
                                                    {branding.address && <span className="flex items-center gap-1"><MapPin className="w-3 h-3" /> {branding.address}</span>}
                                                    {branding.phone && <span className="flex items-center gap-1"><Phone className="w-3 h-3" /> {branding.phone}</span>}
                                                    {branding.website && <span className="flex items-center gap-1"><Globe className="w-3 h-3" /> {branding.website}</span>}
                                                </div>
                                            </div>

                                            {/* Dummy Content Section */}
                                            <div className="space-y-4 py-6">
                                                <div className="h-4 bg-slate-100 rounded w-1/4"></div>
                                                <div className="space-y-2 opacity-10">
                                                    <div className="h-3 bg-slate-900 rounded w-full"></div>
                                                    <div className="h-3 bg-slate-900 rounded w-5/6"></div>
                                                </div>
                                            </div>

                                            {/* Footer Preview */}
                                            <div className="mt-8 pt-6 border-t border-slate-100 text-center">
                                                <p className="text-[11px] text-slate-500 font-medium italic">
                                                    "{branding.footer_template || 'Footer content goes here...'}"
                                                </p>
                                                <div className="mt-4 flex justify-between items-center opacity-40">
                                                    <p className="text-[8px] font-bold text-slate-400">GENERATED BY VOXAI</p>
                                                    <p className="text-[8px] text-slate-400">{new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }).toUpperCase()}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </motion.div>
                        )}
                    </AnimatePresence>

                    <div className="p-4 bg-slate-50 dark:bg-slate-900/50 rounded-xl border border-slate-200 dark:border-slate-800 flex gap-4 items-start">
                        <div className="p-2 bg-white dark:bg-slate-800 rounded-lg shadow-sm border border-slate-100 dark:border-slate-700">
                            <FileText className="text-primary-600 dark:text-primary-400 w-5 h-5" />
                        </div>
                        <div>
                            <p className="text-sm font-bold text-slate-900 dark:text-white">Professional Data Binding</p>
                            <p className="text-xs text-slate-500 mt-0.5">Your specific clinic identity is automatically injected into every consultation report generated by our system.</p>
                        </div>
                    </div>
                </div>

                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        {success && (
                            <motion.div
                                initial={{ opacity: 0, x: -10 }}
                                animate={{ opacity: 1, x: 0 }}
                                className="text-green-500 flex items-center gap-1 text-sm font-bold"
                            >
                                <CheckCircle2 className="w-4 h-4" /> Settings Saved!
                            </motion.div>
                        )}
                    </div>
                    <button
                        type="submit"
                        disabled={saving}
                        className="btn-primary min-w-[200px] flex items-center justify-center gap-2"
                    >
                        {saving ? <Loader2 className="w-5 h-5 animate-spin" /> : <Save className="w-5 h-5" />}
                        Save Branding Settings
                    </button>
                </div>
            </form>
        </div>
    );
};

export default BrandingSettings;
